php:
  build: .
  ports:
    - "8086:80"
    - "8089:443"
  volumes:
    - ./www:/var/www/html
  links:
    - db
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  ports:
    - "8087:80"
db:
  image: mariadb
  ports:
    - "8088:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
